version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        tag: v1.0
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis  # compose 中的服务名
      SPRING_REDIS_PORT: 6379 # redis 服务的端口，默认可以不指定的
